name: Terraform Workflow

on:
 workflow_dispatch: ############## 
 push:
   branches:
     - feature/terraform
jobs:
  terraform:
    runs-on: self-hosted ###ec2-runner-kingsley #ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    
    environment: dev

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.3  

      - name: Initialize Terraform
        run: terraform init -reconfigure

      - name: Plan Terraform
        run: terraform plan

      - name: Apply Terraform
        run: terraform apply -auto-approve

